import React from 'react'

const about = () => {
  return (
    <div>
      This is the about ..
    </div>
  )
}

export default about

export const metadata = {
    title: "about page next learning",
    description: "Generated by create next app",
  };